### ISSUE TITLE
in a borehole array, does surface sensor have a different station_housing code?

### ISSUE THREAD

**Issue by SCEDC** [SCEDC/ground-motion-packet#10]
Should the gmp writer use a different station_housing code for the surface and downhole sensors?

**Comment by steidljh** [comment]
Yes, they should be consistent with the sensors installation. Surface sensors should not have the station_housing code 50. This is why I suggested that we shouldn't have "station_housing" codes, but instead call them "sensor_housing" code.

**Comment by ellenyu** [comment]
This is probably clearer to the user now that stream_depth is also required. Closing issue.
