### ISSUE TITLE
should event use geojson coordinates?

### ISSUE THREAD

**Issue by SCEDC** [SCEDC/ground-motion-packet#6]
the 3rd item in geojson coordinates list is technically defined as height in meters above WGS datum.
This differs from usual convention for an event which is units in km and positive downward. 

[https://datatracker.ietf.org/doc/html/rfc7946#page-12](geojson spec)

If we keep usual convention (different from geojson spec),  it would also be inconsistent with usage of station coordinates.

**Comment by steidljh** [comment]
I think we should probably stick with the geojson spec. If I see and event lat/lon/neg depth of (-10000) I'm going to know this isn't kilometers. I don't know the downstream implications for this with other applications like ShakeMap.

**Comment by SCEDC** [comment]
group is agreement to use elevation in meters as dictated by GeoJSON spec for all features including event.

**Comment by SCEDC** [comment]
resolved in 4b1e545289d8e8135e91a40a8a547319b52fdfeb
