### ISSUE TITLE
add creation_time to top level of document

### ISSUE THREAD

**Issue by SCEDC** [SCEDC/ground-motion-packet#8]
It is important to know when the document was created as some features, such as event might have information evolve over time.

**Comment by steidljh** [comment]
yes, that seems like a good idea. Typically processed data files at CESMD have the time the data was processed.

**Comment by SCEDC** [comment]
propose from Bruce Worden to add to spec:

We have adopted ISO 8601 *extended* format (i.e., with separators between the year, month, and day, and the hour, minutes, and seconds, and with a “T” between the date and time) because it is more human readable. All times must be in UTC, and this fact should be indicated by a “Z” at the end of the datetime string. Fractional seconds are allowed (but neither required nor encouraged), and if used should consist of exactly three digits following the decimal point (which should consist of a dot (period), not a comma). An example of a well-formatted datetime string is:

 

                                “2022-01-16T14:12:32.470Z”

**Comment by SCEDC** [comment]
made change in f5a337aabbd0433783b16dc246a0cafd79abdf75.  Also added to event.md
